### ISSUE TITLE
technical todo stuff

### ISSUE THREAD

**Issue by Catz-uwu** [RasmusAntons/wizard#3]
- [x] delete level button with confirmation dialog and option to delete channel/roles
- [x] use HTTP_AUTHORIZATION header instead of query for authorization
- [x] categories and configurations get an edited marker and are saved with the save button
- [x] readme with setup instructions and explanations of how the site affects discord
